// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJtUPlAsiaKvdS1axfsmciUfchY0GNWaQ',
    appId: '1:109322381201:web:54aa4b62989eab21d81c30',
    messagingSenderId: '109322381201',
    projectId: 'playground-3c810',
    authDomain: 'playground-3c810.firebaseapp.com',
    storageBucket: 'playground-3c810.appspot.com',
    measurementId: 'G-R8FBTJ57MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnw2bM3o7z-otDS__lFUxbRiawXIW0st8',
    appId: '1:109322381201:android:f9e63e23ba795a1dd81c30',
    messagingSenderId: '109322381201',
    projectId: 'playground-3c810',
    storageBucket: 'playground-3c810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbopef_Jbr9GTXgxfpP4Rpp1-G-il4x_k',
    appId: '1:109322381201:ios:d27eb385f8327ca1d81c30',
    messagingSenderId: '109322381201',
    projectId: 'playground-3c810',
    storageBucket: 'playground-3c810.appspot.com',
    iosClientId: '109322381201-2o0qaf85f7rpdffenemc48p4vmd2socd.apps.googleusercontent.com',
    iosBundleId: 'org.holuid.notificationsPlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbopef_Jbr9GTXgxfpP4Rpp1-G-il4x_k',
    appId: '1:109322381201:ios:d27eb385f8327ca1d81c30',
    messagingSenderId: '109322381201',
    projectId: 'playground-3c810',
    storageBucket: 'playground-3c810.appspot.com',
    iosClientId: '109322381201-2o0qaf85f7rpdffenemc48p4vmd2socd.apps.googleusercontent.com',
    iosBundleId: 'org.holuid.notificationsPlayground',
  );
}
